# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pricing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpricing.proto\x12\x07pricing\x1a google/protobuf/descriptor.proto\",\n\rEstimatePrice\x12\x1b\n\x13\x65stimatePriceMethod\x18\x01 \x01(\t\"\x1c\n\x0bPriceInCogs\x12\r\n\x05price\x18\x01 \x01(\x04:S\n\x10my_method_option\x12\x1e.google.protobuf.MethodOptions\x18\x97\xa6\xe2\x04 \x01(\x0b\x32\x16.pricing.EstimatePriceB\x0cZ\n../pricingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pricing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n../pricing'
  _globals['_ESTIMATEPRICE']._serialized_start=60
  _globals['_ESTIMATEPRICE']._serialized_end=104
  _globals['_PRICEINCOGS']._serialized_start=106
  _globals['_PRICEINCOGS']._serialized_end=134
# @@protoc_insertion_point(module_scope)
