# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13token_service.proto\x12\x06\x65scrow\"\x93\x01\n\x0cTokenRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\x04\x12\x15\n\rcurrent_nonce\x18\x02 \x01(\x04\x12\x15\n\rsigned_amount\x18\x03 \x01(\x04\x12\x11\n\tsignature\x18\x04 \x01(\x0c\x12\x15\n\rcurrent_block\x18\x05 \x01(\x04\x12\x17\n\x0f\x63laim_signature\x18\x06 \x01(\x0c\"\\\n\nTokenReply\x12\x12\n\nchannel_id\x18\x01 \x01(\x04\x12\r\n\x05token\x18\x02 \x01(\t\x12\x16\n\x0eplanned_amount\x18\x03 \x01(\x04\x12\x13\n\x0bused_amount\x18\x04 \x01(\x04\x32\x46\n\x0cTokenService\x12\x36\n\x08GetToken\x12\x14.escrow.TokenRequest\x1a\x12.escrow.TokenReply\"\x00\x42!\n\x1fio.singularitynet.daemon.escrowb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'token_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037io.singularitynet.daemon.escrow'
  _globals['_TOKENREQUEST']._serialized_start=32
  _globals['_TOKENREQUEST']._serialized_end=179
  _globals['_TOKENREPLY']._serialized_start=181
  _globals['_TOKENREPLY']._serialized_end=273
  _globals['_TOKENSERVICE']._serialized_start=275
  _globals['_TOKENSERVICE']._serialized_end=345
# @@protoc_insertion_point(module_scope)
