# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import training_daemon_pb2 as training__daemon__pb2
import training_pb2 as training__pb2


class DaemonStub(object):
    """These methods are implemented only by the daemon; the service provider should ignore them
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_model = channel.unary_unary(
                '/training.Daemon/create_model',
                request_serializer=training__daemon__pb2.NewModelRequest.SerializeToString,
                response_deserializer=training__pb2.ModelResponse.FromString,
                )
        self.validate_model_price = channel.unary_unary(
                '/training.Daemon/validate_model_price',
                request_serializer=training__daemon__pb2.AuthValidateRequest.SerializeToString,
                response_deserializer=training__pb2.PriceInBaseUnit.FromString,
                )
        self.upload_and_validate = channel.stream_unary(
                '/training.Daemon/upload_and_validate',
                request_serializer=training__daemon__pb2.UploadAndValidateRequest.SerializeToString,
                response_deserializer=training__pb2.StatusResponse.FromString,
                )
        self.validate_model = channel.unary_unary(
                '/training.Daemon/validate_model',
                request_serializer=training__daemon__pb2.AuthValidateRequest.SerializeToString,
                response_deserializer=training__pb2.StatusResponse.FromString,
                )
        self.train_model_price = channel.unary_unary(
                '/training.Daemon/train_model_price',
                request_serializer=training__daemon__pb2.CommonRequest.SerializeToString,
                response_deserializer=training__pb2.PriceInBaseUnit.FromString,
                )
        self.train_model = channel.unary_unary(
                '/training.Daemon/train_model',
                request_serializer=training__daemon__pb2.CommonRequest.SerializeToString,
                response_deserializer=training__pb2.StatusResponse.FromString,
                )
        self.delete_model = channel.unary_unary(
                '/training.Daemon/delete_model',
                request_serializer=training__daemon__pb2.CommonRequest.SerializeToString,
                response_deserializer=training__pb2.StatusResponse.FromString,
                )
        self.get_all_models = channel.unary_unary(
                '/training.Daemon/get_all_models',
                request_serializer=training__daemon__pb2.AllModelsRequest.SerializeToString,
                response_deserializer=training__daemon__pb2.ModelsResponse.FromString,
                )
        self.get_model = channel.unary_unary(
                '/training.Daemon/get_model',
                request_serializer=training__daemon__pb2.CommonRequest.SerializeToString,
                response_deserializer=training__pb2.ModelResponse.FromString,
                )
        self.update_model = channel.unary_unary(
                '/training.Daemon/update_model',
                request_serializer=training__daemon__pb2.UpdateModelRequest.SerializeToString,
                response_deserializer=training__pb2.ModelResponse.FromString,
                )
        self.get_training_metadata = channel.unary_unary(
                '/training.Daemon/get_training_metadata',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=training__daemon__pb2.TrainingMetadata.FromString,
                )
        self.get_method_metadata = channel.unary_unary(
                '/training.Daemon/get_method_metadata',
                request_serializer=training__daemon__pb2.MethodMetadataRequest.SerializeToString,
                response_deserializer=training__daemon__pb2.MethodMetadata.FromString,
                )


class DaemonServicer(object):
    """These methods are implemented only by the daemon; the service provider should ignore them
    """

    def create_model(self, request, context):
        """Free
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def validate_model_price(self, request, context):
        """Free
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def upload_and_validate(self, request_iterator, context):
        """Paid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def validate_model(self, request, context):
        """Paid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def train_model_price(self, request, context):
        """Free, one signature for both train_model_price & train_model methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def train_model(self, request, context):
        """Paid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete_model(self, request, context):
        """Free
        After deleting the model, the status becomes DELETED in etcd
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_models(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_model(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_model(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_training_metadata(self, request, context):
        """Unique methods by daemon
        One signature for all getters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_method_metadata(self, request, context):
        """Free & without authorization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_model': grpc.unary_unary_rpc_method_handler(
                    servicer.create_model,
                    request_deserializer=training__daemon__pb2.NewModelRequest.FromString,
                    response_serializer=training__pb2.ModelResponse.SerializeToString,
            ),
            'validate_model_price': grpc.unary_unary_rpc_method_handler(
                    servicer.validate_model_price,
                    request_deserializer=training__daemon__pb2.AuthValidateRequest.FromString,
                    response_serializer=training__pb2.PriceInBaseUnit.SerializeToString,
            ),
            'upload_and_validate': grpc.stream_unary_rpc_method_handler(
                    servicer.upload_and_validate,
                    request_deserializer=training__daemon__pb2.UploadAndValidateRequest.FromString,
                    response_serializer=training__pb2.StatusResponse.SerializeToString,
            ),
            'validate_model': grpc.unary_unary_rpc_method_handler(
                    servicer.validate_model,
                    request_deserializer=training__daemon__pb2.AuthValidateRequest.FromString,
                    response_serializer=training__pb2.StatusResponse.SerializeToString,
            ),
            'train_model_price': grpc.unary_unary_rpc_method_handler(
                    servicer.train_model_price,
                    request_deserializer=training__daemon__pb2.CommonRequest.FromString,
                    response_serializer=training__pb2.PriceInBaseUnit.SerializeToString,
            ),
            'train_model': grpc.unary_unary_rpc_method_handler(
                    servicer.train_model,
                    request_deserializer=training__daemon__pb2.CommonRequest.FromString,
                    response_serializer=training__pb2.StatusResponse.SerializeToString,
            ),
            'delete_model': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_model,
                    request_deserializer=training__daemon__pb2.CommonRequest.FromString,
                    response_serializer=training__pb2.StatusResponse.SerializeToString,
            ),
            'get_all_models': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_models,
                    request_deserializer=training__daemon__pb2.AllModelsRequest.FromString,
                    response_serializer=training__daemon__pb2.ModelsResponse.SerializeToString,
            ),
            'get_model': grpc.unary_unary_rpc_method_handler(
                    servicer.get_model,
                    request_deserializer=training__daemon__pb2.CommonRequest.FromString,
                    response_serializer=training__pb2.ModelResponse.SerializeToString,
            ),
            'update_model': grpc.unary_unary_rpc_method_handler(
                    servicer.update_model,
                    request_deserializer=training__daemon__pb2.UpdateModelRequest.FromString,
                    response_serializer=training__pb2.ModelResponse.SerializeToString,
            ),
            'get_training_metadata': grpc.unary_unary_rpc_method_handler(
                    servicer.get_training_metadata,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=training__daemon__pb2.TrainingMetadata.SerializeToString,
            ),
            'get_method_metadata': grpc.unary_unary_rpc_method_handler(
                    servicer.get_method_metadata,
                    request_deserializer=training__daemon__pb2.MethodMetadataRequest.FromString,
                    response_serializer=training__daemon__pb2.MethodMetadata.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'training.Daemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Daemon(object):
    """These methods are implemented only by the daemon; the service provider should ignore them
    """

    @staticmethod
    def create_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/training.Daemon/create_model',
            training__daemon__pb2.NewModelRequest.SerializeToString,
            training__pb2.ModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def validate_model_price(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/training.Daemon/validate_model_price',
            training__daemon__pb2.AuthValidateRequest.SerializeToString,
            training__pb2.PriceInBaseUnit.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def upload_and_validate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/training.Daemon/upload_and_validate',
            training__daemon__pb2.UploadAndValidateRequest.SerializeToString,
            training__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def validate_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/training.Daemon/validate_model',
            training__daemon__pb2.AuthValidateRequest.SerializeToString,
            training__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def train_model_price(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/training.Daemon/train_model_price',
            training__daemon__pb2.CommonRequest.SerializeToString,
            training__pb2.PriceInBaseUnit.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def train_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/training.Daemon/train_model',
            training__daemon__pb2.CommonRequest.SerializeToString,
            training__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/training.Daemon/delete_model',
            training__daemon__pb2.CommonRequest.SerializeToString,
            training__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_all_models(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/training.Daemon/get_all_models',
            training__daemon__pb2.AllModelsRequest.SerializeToString,
            training__daemon__pb2.ModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/training.Daemon/get_model',
            training__daemon__pb2.CommonRequest.SerializeToString,
            training__pb2.ModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/training.Daemon/update_model',
            training__daemon__pb2.UpdateModelRequest.SerializeToString,
            training__pb2.ModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_training_metadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/training.Daemon/get_training_metadata',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            training__daemon__pb2.TrainingMetadata.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_method_metadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/training.Daemon/get_method_metadata',
            training__daemon__pb2.MethodMetadataRequest.SerializeToString,
            training__daemon__pb2.MethodMetadata.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
